[package]
name = "n_array"
version = "0.1.3"
authors = ["Lucille Blumire <llblumire@gmail.com>"]
repository = "https://github.com/SDBlumire/n_array"
description = "Arbitrarily dimensioned arrays"
keywords = ["2d", "3d", "multidimensional", "dimension", "array"]
license = "GPL-2.0+"
